name: Publish Package to npmjs
on:
    workflow_dispatch:
       inputs:
           version:
               required: true
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: npm i
            - run: |
                  git config --global user.name "${{ github.actor }}"
                  git config --global user.email "github-action-${{ github.actor }}@users.noreply.github.com"
            - run: |
                  npm version ${{ github.events.inputs.version }}
                  git push origin main
                  git push origin v${{ github.events.inputs.version }}
            - run: npm run build
            - run: npm publish --provenance --access public
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
